// demo/web/packages/xyncra-client-web/src/components/FloatingAssistant/HITLDialog.tsx
/**
 * @packageDocumentation
 * HITLDialog — Human-in-the-Loop confirmation dialog.
 *
 * When the agent raises HITL questions, this modal appears with all
 * questions displayed in tabs. All questions must be answered before
 * submission is allowed.
 *
 * @module
 */

import { Form, Input, Modal, Tabs, message } from 'antd';
import { useCallback, useEffect, useState } from 'react';
import { useHITL } from '../../hooks/useHITL';

/**
 * Renders the HITL dialog when pending questions exist.
 * Returns null when there are no pending questions.
 */
export function HITLDialog({ conversationId }: { conversationId?: string }): React.JSX.Element | null {
  const { pendingQuestions, answerAll, dismiss, isSubmitting } = useHITL(conversationId);
  const [form] = Form.useForm();
  const [activeTab, setActiveTab] = useState<string>('0');

  // Reset form when questions change
  useEffect(() => {
    form.resetFields();
    setActiveTab('0');
  }, [pendingQuestions, form]);

  const handleOk = useCallback(async () => {
    if (pendingQuestions.length === 0) return;

    try {
      const values = await form.validateFields();
      const answers = new Map<string, string>();

      // Collect all answers
      pendingQuestions.forEach((q, index) => {
        const answerKey = `answer_${index}`;
        const answerText = values[answerKey];
        if (answerText && q.questionId) {
          answers.set(q.questionId, answerText);
        }
      });

      await answerAll(answers);
      form.resetFields();
      message.success('所有问题已回答');
    } catch (error) {
      if (error && typeof error === 'object' && 'errorFields' in error) {
        // Form validation error - find which tab has the error
        const errorFields = (error as { errorFields: Array<{ name: string[] }> }).errorFields;
        if (errorFields.length > 0) {
          const fieldName = errorFields[0].name[0];
          const tabIndex = fieldName.replace('answer_', '');
          setActiveTab(tabIndex);
        }
        message.error('请填写所有问题的回答');
      } else {
        message.error('提交失败：' + (error instanceof Error ? error.message : String(error)));
      }
    }
  }, [pendingQuestions, form, answerAll]);

  if (pendingQuestions.length === 0) return null;

  // Check if all questions are answered
  const formValues = form.getFieldsValue();
  const allAnswered = pendingQuestions.every((_, index) => {
    const answerKey = `answer_${index}`;
    return formValues[answerKey] && formValues[answerKey].trim() !== '';
  });

  const tabItems = pendingQuestions.map((q, index) => ({
    key: String(index),
    label: `问题 ${index + 1}`,
    children: (
      <div>
        <Form.Item label="问题">
          <div
            style={{
              padding: 12,
              backgroundColor: '#fafafa',
              borderRadius: 6,
            }}
          >
            {q.question}
          </div>
        </Form.Item>
        <Form.Item
          name={`answer_${index}`}
          label="您的回答"
          rules={[{ required: true, message: '请输入您的回答' }]}
        >
          <Input.TextArea rows={4} placeholder="请输入..." />
        </Form.Item>
      </div>
    ),
  }));

  return (
    <Modal
      title={`需要您的确认（${pendingQuestions.length} 个问题）`}
      open={pendingQuestions.length > 0}
      onOk={() => {
        void handleOk();
      }}
      onCancel={() => {
        dismiss();
        form.resetFields();
      }}
      okText={isSubmitting ? '提交中...' : '提交全部'}
      cancelText="取消"
      confirmLoading={isSubmitting}
      okButtonProps={{ disabled: !allAnswered || isSubmitting }}
      width={600}
    >
      <Form form={form} layout="vertical">
        <Tabs
          activeKey={activeTab}
          onChange={setActiveTab}
          items={tabItems}
          type="card"
        />
      </Form>
    </Modal>
  );
}

// demo/vue-pure-admin/packages/xyncra-client-vue/src/components/HITLDialog.vue
<template>
  <el-dialog
    :model-value="visible"
    :title="`需要您的确认（${questions.length} 个问题）`"
    width="600px"
    :close-on-click-modal="false"
    @update:model-value="$emit('update:visible', $event)"
    @close="handleClose"
  >
    <div v-if="questions.length > 0" class="hitl-content">
      <el-tabs v-model="activeTab" type="card" class="hitl-tabs">
        <el-tab-pane
          v-for="(q, index) in questions"
          :key="q.questionId ?? index"
          :label="`问题 ${index + 1}`"
          :name="String(index)"
        >
          <div class="hitl-question-block">
            <div class="hitl-question-label">问题</div>
            <div class="hitl-question-text">{{ q.question }}</div>
            <div class="hitl-answer-section">
              <div class="hitl-answer-label">您的回答</div>
              <el-input
                v-model="answers[index]"
                type="textarea"
                :rows="4"
                placeholder="请输入..."
                :disabled="isSubmitting"
              />
            </div>
          </div>
        </el-tab-pane>
      </el-tabs>
      <div class="hitl-queue-status">
        <span>{{ answeredCount }} / {{ questions.length }} 已填写</span>
      </div>
    </div>
    <div v-else class="hitl-empty">
      <p>没有待处理的审批请求</p>
    </div>
    <template #footer>
      <el-button @click="handleDismiss" :disabled="isSubmitting">
        取消
      </el-button>
      <el-button
        type="primary"
        :loading="isSubmitting"
        :disabled="!allAnswered || isSubmitting"
        @click="handleSubmit"
      >
        {{ isSubmitting ? '提交中...' : '提交全部' }}
      </el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { ElMessage } from 'element-plus'
import type { HITLQuestion } from '../composables/useHITL'

const props = defineProps<{
  visible: boolean
  questions: HITLQuestion[]
  isSubmitting?: boolean
}>()

const emit = defineEmits<{
  'update:visible': [value: boolean]
  submit: [answers: Map<string, string>]
  dismiss: []
}>()

const activeTab = ref('0')
const answers = ref<string[]>([])

// Reset answers when questions change
watch(() => props.questions.length, (newLen) => {
  answers.value = Array.from({ length: newLen }, () => '')
  activeTab.value = '0'
}, { immediate: true })

const answeredCount = computed(() => {
  return answers.value.filter(a => a && a.trim() !== '').length
})

const allAnswered = computed(() => {
  return props.questions.length > 0 &&
    answers.value.every(a => a && a.trim() !== '')
})

function handleSubmit() {
  if (!allAnswered.value) {
    ElMessage.warning('请填写所有问题的回答')
    return
  }

  const answersMap = new Map<string, string>()
  props.questions.forEach((q, index) => {
    const answerText = answers.value[index]
    if (answerText && q.questionId) {
      answersMap.set(q.questionId, answerText)
    }
  })

  emit('submit', answersMap)
}

function handleDismiss() {
  emit('dismiss')
  emit('update:visible', false)
}

function handleClose() {
  emit('update:visible', false)
}
</script>

<style scoped>
.hitl-content {
  padding: 4px 0;
}
.hitl-tabs {
  margin-bottom: 12px;
}
.hitl-question-block {
  padding: 8px 0;
}
.hitl-question-label,
.hitl-answer-label {
  font-size: 13px;
  font-weight: 500;
  color: var(--el-text-color-regular);
  margin-bottom: 8px;
}
.hitl-question-text {
  padding: 12px;
  background-color: var(--el-fill-color-light, #fafafa);
  border-radius: 6px;
  font-size: 14px;
  line-height: 1.6;
  color: var(--el-text-color-primary);
  margin-bottom: 16px;
}
.hitl-answer-section {
  margin-top: 8px;
}
.hitl-queue-status {
  text-align: center;
  font-size: 12px;
  color: var(--el-text-color-secondary);
  padding-top: 4px;
}
.hitl-empty {
  text-align: center;
  padding: 24px 0;
  color: var(--el-text-color-secondary);
}
</style>
